#!/bin/sh
#
# @name SIMAR Gazebo
# @type Hexarotor x
# @class Copter
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=SIMAR}

param set-default CA_AIRFRAME 0

param set-default SYS_AUTOSTART 6010


param set-default MPC_OMNI_MODE 0

# Configuramos que tiene 6 rotores y geometría en X
# Número de rotores
param set-default CA_ROTOR_COUNT 6
param set-default CA_R_REV 0

# Orden: igual que en tu SDF (0–5)
# =========================================================
# GEOMETRÍA CORREGIDA PARA DJI F550 (Hexa X)
# =========================================================

param set-default MPC_ACC_HOR 3.2

param set-default MPC_XY_VEL_MAX 8.0
param set-default MPC_XY_CRUISE 8.0

param set-default MPC_XY_VEL_P_ACC 2.0
param set-default MPC_XY_VEL_D_ACC 0.3

param set-default MPC_XY_P 0.95

param set-default MPC_JERK_MAX 6.0
param set-default MPC_JERK_AUTO 10.0

param set-default MC_YAWRATE_P 0.05
param set-default MPC_YAWRAUTO_ACC 20.0
param set-default MPC_YAWRAUTO_MAX 60.0
param set-default MC_YAW_P 0.8
param set-default MC_YAW_WEIGHT 0.4



param set-default CA_ROTOR0_PX 0.0
param set-default CA_ROTOR0_PY 0.275
param set-default CA_ROTOR0_PZ 0.0
param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR0_AX 0.321
param set-default CA_ROTOR0_AY 0.342
param set-default CA_ROTOR0_AZ -0.883

param set-default CA_ROTOR1_PX 0.0
param set-default CA_ROTOR1_PY -0.275
param set-default CA_ROTOR1_PZ 0.0
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR1_AX 0.321
param set-default CA_ROTOR1_AY 0.342
param set-default CA_ROTOR1_AZ -0.883

param set-default CA_ROTOR2_PX 0.238
param set-default CA_ROTOR2_PY -0.1375
param set-default CA_ROTOR2_PZ 0.0
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR2_AX 0.136
param set-default CA_ROTOR2_AY -0.449
param set-default CA_ROTOR2_AZ -0.883

param set-default CA_ROTOR3_PX -0.238
param set-default CA_ROTOR3_PY 0.1375
param set-default CA_ROTOR3_PZ 0.0
param set-default CA_ROTOR3_KM 0.05
param set-default CA_ROTOR3_AX 0.136
param set-default CA_ROTOR3_AY -0.449
param set-default CA_ROTOR3_AZ -0.883

param set-default CA_ROTOR4_PX 0.238
param set-default CA_ROTOR4_PY 0.1375
param set-default CA_ROTOR4_PZ 0.0
param set-default CA_ROTOR4_KM 0.05
param set-default CA_ROTOR4_AX -0.457
param set-default CA_ROTOR4_AY 0.107
param set-default CA_ROTOR4_AZ -0.883

param set-default CA_ROTOR5_PX -0.238
param set-default CA_ROTOR5_PY -0.1375
param set-default CA_ROTOR5_PZ 0.0
param set-default CA_ROTOR5_KM -0.05
param set-default CA_ROTOR5_AX -0.457
param set-default CA_ROTOR5_AY 0.107
param set-default CA_ROTOR5_AZ -0.883


param set-default SIM_GZ_EN 1

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MIN5 150
param set-default SIM_GZ_EC_MIN6 150

param set-default SIM_GZ_EC_MAX1 1100
param set-default SIM_GZ_EC_MAX2 1100
param set-default SIM_GZ_EC_MAX3 1100
param set-default SIM_GZ_EC_MAX4 1100
param set-default SIM_GZ_EC_MAX5 1100
param set-default SIM_GZ_EC_MAX6 1100



# disable MC desaturation which improves attitude tracking
param set-default CA_METHOD 0
