#!/bin/sh
#
# @name SIMAR Gazebo
# @type Hexarotor x
# @class Copter
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=SIMAR}

# ❗ IMPORTANTE: sin control allocation de PX4 (usarás el tuyo)
param set-default CA_AIRFRAME 0

param set-default SYS_AUTOSTART 6011
param set-default MPC_OMNI_MODE 0

# =========================================================
# CONFIGURACIÓN DE CONTROL (puedes ajustarlo luego)
# =========================================================

param set-default MPC_ACC_HOR 3.2
param set-default MPC_XY_VEL_MAX 8.0
param set-default MPC_XY_CRUISE 8.0
param set-default MPC_XY_VEL_P_ACC 2.0
param set-default MPC_XY_VEL_D_ACC 0.3
param set-default MPC_XY_P 0.95
param set-default MPC_JERK_MAX 6.0
param set-default MPC_JERK_AUTO 10.0

param set-default MC_YAWRATE_P 0.05
param set-default MPC_YAWRAUTO_ACC 20.0
param set-default MPC_YAWRAUTO_MAX 60.0
param set-default MC_YAW_P 0.8
param set-default MC_YAW_WEIGHT 0.4

# =========================================================
# GEOMETRÍA HEXA (solo informativa para tu módulo)
# =========================================================

param set-default CA_ROTOR_COUNT 6
param set-default CA_R_REV 0

param set-default CA_ROTOR0_PX 0.0
param set-default CA_ROTOR0_PY 0.275
param set-default CA_ROTOR0_PZ 0.0
param set-default CA_ROTOR0_KM -0.05

param set-default CA_ROTOR1_PX 0.0
param set-default CA_ROTOR1_PY -0.275
param set-default CA_ROTOR1_PZ 0.0
param set-default CA_ROTOR1_KM 0.05

param set-default CA_ROTOR2_PX 0.238
param set-default CA_ROTOR2_PY -0.1375
param set-default CA_ROTOR2_PZ 0.0
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.238
param set-default CA_ROTOR3_PY 0.1375
param set-default CA_ROTOR3_PZ 0.0
param set-default CA_ROTOR3_KM 0.05

param set-default CA_ROTOR4_PX 0.238
param set-default CA_ROTOR4_PY 0.1375
param set-default CA_ROTOR4_PZ 0.0
param set-default CA_ROTOR4_KM 0.05

param set-default CA_ROTOR5_PX -0.238
param set-default CA_ROTOR5_PY -0.1375
param set-default CA_ROTOR5_PZ 0.0
param set-default CA_ROTOR5_KM -0.05

# =========================================================
# GAZEBO SIM
# =========================================================

param set-default SIM_GZ_EN 1

# Motores (ESC)
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106

# Servos (tilt independientes)
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204
param set-default SIM_GZ_SV_FUNC5 205
param set-default SIM_GZ_SV_FUNC6 206

# Límites de ángulo (puedes ajustar luego)
param set-default SIM_GZ_SV_MINA1 -360
param set-default SIM_GZ_SV_MAXA1 360
param set-default SIM_GZ_SV_MINA2 -360
param set-default SIM_GZ_SV_MAXA2 360
param set-default SIM_GZ_SV_MINA3 -360
param set-default SIM_GZ_SV_MAXA3 360
param set-default SIM_GZ_SV_MINA4 -360
param set-default SIM_GZ_SV_MAXA4 360
param set-default SIM_GZ_SV_MINA5 -360
param set-default SIM_GZ_SV_MAXA5 360
param set-default SIM_GZ_SV_MINA6 -360
param set-default SIM_GZ_SV_MAXA6 360

# =========================================================
# OTROS
# =========================================================

param set-default CA_METHOD 0
param set-default FD_FAIL_P 0
param set-default FD_FAIL_R 0
